services:
  mysql:
    image: mariadb:10.11
    container_name: crypto-trading-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crypto_trading
      MYSQL_USER: crypto_user
      MYSQL_PASSWORD: crypto_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - crypto-trading-network

  redis:
    image: redis:7-alpine
    container_name: crypto-trading-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - crypto-trading-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crypto-trading-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: crypto_user
      PMA_PASSWORD: crypto_password
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - crypto-trading-network

volumes:
  mysql_data:
  redis_data:

networks:
  crypto-trading-network:
    driver: bridge